language: node_js
node_js:
  - '10'
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
cache:
  yarn: true
notifications:
  email: false
script:
  - yarn dist
addons:
  apt:
    packages:
    - libusb-1.0-0-dev
    - libudev-dev
deploy:
  provider: releases
  api_key: GH_TOKEN
  file:
  - "./release/*.zip"
  - "./release/*.dmg"
  - "./release/*.AppImage"
  - "./release/*.deb"
  - "./release/*.tar.xz"
  skip_cleanup: true
  draft: true
  on:
    tags: true
